//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class abteilungen
    {
        public abteilungen()
        {
            this.fahrzeuge = new HashSet<fahrzeuge>();
            this.nutzer = new HashSet<nutzer>();
        }
    
        public int abteilungID { get; set; }
        public string abteilung { get; set; }
        public int firmaID { get; set; }
        public string abteilungbeschr { get; set; }
    
        public virtual firmen firmen { get; set; }
        public virtual ICollection<fahrzeuge> fahrzeuge { get; set; }
        public virtual ICollection<nutzer> nutzer { get; set; }
    }
}
