//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeuge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fahrzeuge()
        {
            this.Simnutzung = new HashSet<Simnutzung>();
        }
    
        public int fahrzeugID { get; set; }
        public string fahrzeugkennzeichen { get; set; }
        public string fahrzeugmodell { get; set; }
        public Nullable<int> abteilungID { get; set; }
        public string fahrzeugnotiz { get; set; }
    
        public virtual Abteilungen Abteilungen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simnutzung> Simnutzung { get; set; }
    }
}
