//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class firmen
    {
        public firmen()
        {
            this.abteilungen = new HashSet<abteilungen>();
        }
    
        public int firmaID { get; set; }
        public string firmaname1 { get; set; }
        public string firmaname2 { get; set; }
        public string strasse { get; set; }
        public string plz { get; set; }
        public string ort { get; set; }
        public string land { get; set; }
        public string ansprechpartner { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string web { get; set; }
        public string firmanotiz { get; set; }
    
        public virtual ICollection<abteilungen> abteilungen { get; set; }
    }
}
