//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class geraetemodelle
    {
        public geraetemodelle()
        {
            this.geraete = new HashSet<geraete>();
        }
    
        public int geraetemodellID { get; set; }
        public string geraetemodell { get; set; }
        public string geraetemodellbeschr { get; set; }
    
        public virtual ICollection<geraete> geraete { get; set; }
    }
}
