//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class geraete
    {
        public geraete()
        {
            this.simnutzung = new HashSet<simnutzung>();
        }
    
        public int geraeteID { get; set; }
        public string geraetenr { get; set; }
        public string geraeteinventarnr { get; set; }
        public string geraeteimei { get; set; }
        public int geraetetypID { get; set; }
        public Nullable<int> geraeteherstID { get; set; }
        public Nullable<int> geraetemodellID { get; set; }
        public Nullable<int> simgroesseID { get; set; }
        public Nullable<int> betriebssysID { get; set; }
        public Nullable<System.DateTime> inbetriebnahme { get; set; }
        public string geraetenotiz { get; set; }
    
        public virtual betriebssysteme betriebssysteme { get; set; }
        public virtual geraetehersteller geraetehersteller { get; set; }
        public virtual geraetemodelle geraetemodelle { get; set; }
        public virtual geraetetypen geraetetypen { get; set; }
        public virtual simgroessen simgroessen { get; set; }
        public virtual ICollection<simnutzung> simnutzung { get; set; }
    }
}
