//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class geraetetypen
    {
        public geraetetypen()
        {
            this.geraete = new HashSet<geraete>();
        }
    
        public int geraetetypID { get; set; }
        public string geraetetyp { get; set; }
        public string geraetetypbeschr { get; set; }
    
        public virtual ICollection<geraete> geraete { get; set; }
    }
}
