//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class netze
    {
        public netze()
        {
            this.telefonnummern = new HashSet<telefonnummern>();
        }
    
        public int netzID { get; set; }
        public string netzname { get; set; }
        public string netzbeschr { get; set; }
    
        public virtual ICollection<telefonnummern> telefonnummern { get; set; }
    }
}
