//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class nutzer
    {
        public nutzer()
        {
            this.simnutzung = new HashSet<simnutzung>();
        }
    
        public int nutzerID { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public int abteilungID { get; set; }
        public string nutzernotiz { get; set; }
    
        public virtual abteilungen abteilungen { get; set; }
        public virtual ICollection<simnutzung> simnutzung { get; set; }
    }
}
