//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class simgroessen
    {
        public simgroessen()
        {
            this.geraete = new HashSet<geraete>();
            this.simkarten = new HashSet<simkarten>();
        }
    
        public int simgroesseID { get; set; }
        public string simgroesse { get; set; }
        public string simgroessebeschr { get; set; }
    
        public virtual ICollection<geraete> geraete { get; set; }
        public virtual ICollection<simkarten> simkarten { get; set; }
    }
}
