//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class simkarten
    {
        public simkarten()
        {
            this.simnutzung = new HashSet<simnutzung>();
        }
    
        public int simkartenID { get; set; }
        public string simkartennr { get; set; }
        public string pin1 { get; set; }
        public string puk1 { get; set; }
        public string pin2 { get; set; }
        public string puk2 { get; set; }
        public Nullable<int> simgroesseID { get; set; }
        public int telnrID { get; set; }
        public string simkartennotiz { get; set; }
    
        public virtual simgroessen simgroessen { get; set; }
        public virtual telefonnummern telefonnummern { get; set; }
        public virtual ICollection<simnutzung> simnutzung { get; set; }
    }
}
