//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class simnutzung
    {
        public int simnutzungID { get; set; }
        public int simkartenID { get; set; }
        public Nullable<int> geraeteID { get; set; }
        public Nullable<int> nutzerID { get; set; }
        public Nullable<int> fahrzeugID { get; set; }
        public System.DateTime simausgabe { get; set; }
        public Nullable<System.DateTime> simrueckgabe { get; set; }
        public string simnutzungnotiz { get; set; }
    
        public virtual fahrzeuge fahrzeuge { get; set; }
        public virtual geraete geraete { get; set; }
        public virtual nutzer nutzer { get; set; }
        public virtual simkarten simkarten { get; set; }
    }
}
