//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simnutzung
    {
        public int simnutzungID { get; set; }
        public int simkartenID { get; set; }
        public Nullable<int> geraeteID { get; set; }
        public Nullable<int> nutzerID { get; set; }
        public Nullable<int> fahrzeugID { get; set; }
        public System.DateTime simausgabe { get; set; }
        public Nullable<System.DateTime> simrueckgabe { get; set; }
        public string simnutzungnotiz { get; set; }
    
        public virtual Fahrzeuge Fahrzeuge { get; set; }
        public virtual Geraete Geraete { get; set; }
        public virtual Nutzer Nutzer { get; set; }
        public virtual Simkarten Simkarten { get; set; }
    }
}
