//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifoptionen
    {
        public tarifoptionen()
        {
            this.vertraege = new HashSet<vertraege>();
            this.vertraege1 = new HashSet<vertraege>();
            this.vertraege2 = new HashSet<vertraege>();
        }
    
        public int tarifoptionID { get; set; }
        public string tarifoptionname { get; set; }
        public string tarifoptionbeschr { get; set; }
    
        public virtual ICollection<vertraege> vertraege { get; set; }
        public virtual ICollection<vertraege> vertraege1 { get; set; }
        public virtual ICollection<vertraege> vertraege2 { get; set; }
    }
}
