//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonnummern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefonnummern()
        {
            this.Simkarten = new HashSet<Simkarten>();
            this.Verbrauch = new HashSet<Verbrauch>();
        }
    
        public int telnrID { get; set; }
        public string telnr { get; set; }
        public int vertragID { get; set; }
        public Nullable<int> netzID { get; set; }
        public string telnrnotiz { get; set; }
    
        public virtual Netze Netze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simkarten> Simkarten { get; set; }
        public virtual Vertraege Vertraege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verbrauch> Verbrauch { get; set; }
    }
}
