//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefonnummern
    {
        public telefonnummern()
        {
            this.simkarten = new HashSet<simkarten>();
            this.verbrauch = new HashSet<verbrauch>();
        }
    
        public int telnrID { get; set; }
        public string telnr { get; set; }
        public int vertragID { get; set; }
        public Nullable<int> netzID { get; set; }
        public string telnrnotiz { get; set; }
    
        public virtual netze netze { get; set; }
        public virtual ICollection<simkarten> simkarten { get; set; }
        public virtual vertraege vertraege { get; set; }
        public virtual ICollection<verbrauch> verbrauch { get; set; }
    }
}
