//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerMobiEntities : DbContext
    {
        public VerMobiEntities()
            : base("name=VerMobiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abteilungen> Abteilungen { get; set; }
        public virtual DbSet<Betriebssysteme> Betriebssysteme { get; set; }
        public virtual DbSet<Fahrzeuge> Fahrzeuge { get; set; }
        public virtual DbSet<Firmen> Firmen { get; set; }
        public virtual DbSet<Geraete> Geraete { get; set; }
        public virtual DbSet<Geraetehersteller> Geraetehersteller { get; set; }
        public virtual DbSet<Geraetemodelle> Geraetemodelle { get; set; }
        public virtual DbSet<Geraetetypen> Geraetetypen { get; set; }
        public virtual DbSet<Netze> Netze { get; set; }
        public virtual DbSet<Nutzer> Nutzer { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Simgroessen> Simgroessen { get; set; }
        public virtual DbSet<Simkarten> Simkarten { get; set; }
        public virtual DbSet<Simnutzung> Simnutzung { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarife> Tarife { get; set; }
        public virtual DbSet<Tarifoptionen> Tarifoptionen { get; set; }
        public virtual DbSet<Telefonnummern> Telefonnummern { get; set; }
        public virtual DbSet<Verbrauch> Verbrauch { get; set; }
        public virtual DbSet<Verkaeufer> Verkaeufer { get; set; }
        public virtual DbSet<Vertraege> Vertraege { get; set; }
        public virtual DbSet<Vertragsarten> Vertragsarten { get; set; }
    }
}
