//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerMobiEntities : DbContext
    {
        public VerMobiEntities()
            : base("name=VerMobiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abteilungen> abteilungen { get; set; }
        public DbSet<betriebssysteme> betriebssysteme { get; set; }
        public DbSet<fahrzeuge> fahrzeuge { get; set; }
        public DbSet<firmen> firmen { get; set; }
        public DbSet<geraete> geraete { get; set; }
        public DbSet<geraetehersteller> geraetehersteller { get; set; }
        public DbSet<geraetemodelle> geraetemodelle { get; set; }
        public DbSet<geraetetypen> geraetetypen { get; set; }
        public DbSet<netze> netze { get; set; }
        public DbSet<nutzer> nutzer { get; set; }
        public DbSet<provider> provider { get; set; }
        public DbSet<simgroessen> simgroessen { get; set; }
        public DbSet<simkarten> simkarten { get; set; }
        public DbSet<simnutzung> simnutzung { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tarife> tarife { get; set; }
        public DbSet<tarifoptionen> tarifoptionen { get; set; }
        public DbSet<telefonnummern> telefonnummern { get; set; }
        public DbSet<verbrauch> verbrauch { get; set; }
        public DbSet<verkaeufer> verkaeufer { get; set; }
        public DbSet<vertraege> vertraege { get; set; }
        public DbSet<vertragsarten> vertragsarten { get; set; }
    }
}
