//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerMobi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vertraege
    {
        public vertraege()
        {
            this.telefonnummern = new HashSet<telefonnummern>();
        }
    
        public int vertragID { get; set; }
        public string vertragsnr { get; set; }
        public int vertragsartID { get; set; }
        public Nullable<int> verkaeuferID { get; set; }
        public int providerID { get; set; }
        public System.DateTime vertragsbeginn { get; set; }
        public Nullable<System.DateTime> kuendigungsfrist { get; set; }
        public Nullable<System.DateTime> gekuendigtam { get; set; }
        public Nullable<System.DateTime> gekuendigtzum { get; set; }
        public Nullable<System.DateTime> vertragsende { get; set; }
        public int tarifID { get; set; }
        public Nullable<decimal> datenvolumeninkl { get; set; }
        public Nullable<System.TimeSpan> telefonieinkl { get; set; }
        public Nullable<decimal> smsinkl { get; set; }
        public Nullable<decimal> grundpreis { get; set; }
        public Nullable<int> tarifoptionID1 { get; set; }
        public Nullable<int> tarifoptionID2 { get; set; }
        public Nullable<int> tarifoptionID3 { get; set; }
        public string vertragsnotiz { get; set; }
    
        public virtual provider provider { get; set; }
        public virtual tarife tarife { get; set; }
        public virtual tarifoptionen tarifoptionen { get; set; }
        public virtual tarifoptionen tarifoptionen1 { get; set; }
        public virtual tarifoptionen tarifoptionen2 { get; set; }
        public virtual ICollection<telefonnummern> telefonnummern { get; set; }
        public virtual verkaeufer verkaeufer { get; set; }
        public virtual vertragsarten vertragsarten { get; set; }
    }
}
